### ISSUE TITLE
IdsForm: Components style issues when resizing the form

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2128]
**Describe the bug**
When setting the `compact` to `true` or `fieldHeight` to `xs/sm`, some of the components inside encounters some style issues.

1. General - button highlight in the input fields are little bit off when `fieldHeight` is set to `xs`
2. Dropdown - selected text is being repeated on the right side when setting either `compact` to true or `fieldHeight` to `xs/sm`
3. Color picker - dirty tracker is way off when when setting either `compact` to true or `fieldHeight` to `xs/sm`

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-form/example.html
2. Click **Toggle Compact**
3. See additional text in the right side of the **Multiselect** field
4. Change something in the **Ship Color**
5. See dirty tracker is way off to the right
6. Open developer's console
7. Enter `document.querySelector('#sample-form').fieldHeight = 'xs'` in the console
8. Hover on the buttons inside each field
9. See highlighting is way off to the right 

**Expected behavior**
No style issues are found when resizing the form

**Screenshots**
**General**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/2aaf8371-2bc6-4d51-871b-e59e982982e8)

**Color picker**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/d862ff0b-ed2f-4238-9a99-42c9e4a689a5)

**Multiselect**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/24b9b05a-c6c3-4225-88d0-854a9b683fd4)
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/48cac6f2-24b3-41d2-9e8b-080a17c1239c)

**Comment by tmcconechy** [comment]
Fixed on https://github.com/infor-design/enterprise-wc/commit/e880ef36494baa6687da479c24bc24141156cca7 Please have a look

**Comment by glenlieorillo** [comment]
Issue on dirty tracker still exists after pasting `document.querySelector('#sample-form').fieldHeight = 'xs'` in the console.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/10a2fcdb-5924-475a-897f-72d8382edeea)

**Comment by tmcconechy** [comment]
@glenlieorillo i'll circle back on that one later
