### ISSUE TITLE
IdsDropdown: input beforetriggerclicked event being fired multiple times

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2576]
**Describe the bug**
IdsDropdown input beforetriggerclicked event being fired multiple times when client on the input.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-dropdown/example.html
2. Register the event for the first combo on console:
```javascript
document.getElementById('dropdown-1').input.addEventListener('beforetriggerclicked', function() {
    console.log('before trigger click')
});
```
3. Click on the trigger (arrow down button), the event happens once (GOOD)
4. Click on the input, the event happens AND twice (BUG)

**Expected behavior**
The event happen only once and only when clicking on the trigger (to expand down the list to show the combo data). Do not fire the event on any other click of input of anywhere else.

**Version**
Latest

**Screenshots**
![Screen Shot 2024-07-10 at 6 03 33 PM](https://github.com/infor-design/enterprise-wc/assets/663908/e17fc671-31df-4b53-bb2f-1e4e89a535ee)

**Comment by fabiojpoli** [comment]
@tmcconechy looks like this one was already fixed automatically when fixed another related issue? Please check. Thanks

**Comment by tmcconechy** [comment]
@fabiojpoli i still see two events when i click on the input part

![Screenshot 2024-08-08 at 10 49 30 AM](https://github.com/user-attachments/assets/838bd04b-9e55-44f3-8dda-3715c4cff3c2)

**Comment by fabiojpoli** [comment]
Oh sorry, never mind, I forgot the issue comes from clicking on input.
